// packages/samples/shared/components/codeInput.svelte
<script lang="ts">
  interface Props {
    length?: number;
    buttonText?: string;
    disabled?: boolean;
    onsubmit?: (event: SubmitEvent) => void;
  }

  let { length = 6, buttonText = "Verify", disabled = false, onsubmit }: Props = $props();

  let value = $state("");

  function handleInput(event: Event) {
    const input = event.target as HTMLInputElement;
    value = input.value.replace(/[^0-9]/g, "").slice(0, length);
    input.value = value;
  }
</script>

{#if onsubmit}
  <form method="POST" {onsubmit}>
    <label>
      Verification code
      <input
        type="text"
        name="code"
        inputmode="numeric"
        autocomplete="one-time-code"
        pattern="[0-9]*"
        minlength={length}
        maxlength={length}
        required
        {disabled}
        oninput={handleInput}
        value={value}
      />
    </label>
    <button type="submit" {disabled}>{buttonText}</button>
  </form>
{:else}
  <form method="POST">
    <label>
      Verification code
      <input
        type="text"
        name="code"
        inputmode="numeric"
        autocomplete="one-time-code"
        pattern="[0-9]*"
        minlength={length}
        maxlength={length}
        required
        {disabled}
        oninput={handleInput}
        value={value}
      />
    </label>
    <button type="submit" {disabled}>{buttonText}</button>
  </form>
{/if}

// packages/samples/authSpaWithApi/site/src/components/codeInput.tsx
import { useState } from "react";

interface Props {
  onSubmit: (event: React.SyntheticEvent<HTMLFormElement>) => void;
  disabled?: boolean;
  length?: number;
}

export function CodeInput({ onSubmit, disabled = false, length = 6 }: Props) {
  const [value, setValue] = useState("");

  function handleChange(event: React.ChangeEvent<HTMLInputElement>) {
    const cleaned = event.target.value.replace(/[^0-9]/g, "").slice(0, length);
    setValue(cleaned);
  }

  return (
    <form onSubmit={onSubmit}>
      <label>
        Verification code
        <input
          type="text"
          name="code"
          inputMode="numeric"
          autoComplete="one-time-code"
          pattern="[0-9]*"
          minLength={length}
          maxLength={length}
          required
          disabled={disabled}
          value={value}
          onChange={handleChange}
        />
      </label>
      <button type="submit" disabled={disabled}>
        Verify
      </button>
    </form>
  );
}
